-- Migration: add category column and replace product catalog
-- Run once on the live VPS database:
--   docker exec -i bakery_postgres psql -U oos_admin -d oos_db < oos/database/migrate_add_categories.sql

ALTER TABLE products ADD COLUMN IF NOT EXISTS category VARCHAR(100) NOT NULL DEFAULT 'Pan dulce';

-- Clear old products (safe only if order_items has no FK violations — wipe order_items first if needed)
TRUNCATE products RESTART IDENTITY CASCADE;

INSERT INTO products (product_name, price, category) VALUES
    ('Babka',                                   0.00, 'Pan dulce'),
    ('Bisquet',                                 0.00, 'Pan dulce'),
    ('Chocolatín',                              0.00, 'Pan dulce'),
    ('Chocolatín almendrado',                   0.00, 'Pan dulce'),
    ('Concha bicolor',                          0.00, 'Pan dulce'),
    ('Concha canela',                           0.00, 'Pan dulce'),
    ('Concha chocolate',                        0.00, 'Pan dulce'),
    ('Concha vainilla',                         0.00, 'Pan dulce'),
    ('Croissant',                               0.00, 'Pan dulce'),
    ('Croissant almendra',                      0.00, 'Pan dulce'),
    ('Flan parisién',                           0.00, 'Pan dulce'),
    ('Flor de limón',                           0.00, 'Pan dulce'),
    ('Galette blueberry',                       0.00, 'Pan dulce'),
    ('Galleta chocochips',                      0.00, 'Pan dulce'),
    ('Galleta chocochips vegana',               0.00, 'Pan dulce'),
    ('Galleta red velvet',                      0.00, 'Pan dulce'),
    ('Galleta vegana avena',                    0.00, 'Pan dulce'),
    ('Galleta vegana doble chocolate',          0.00, 'Pan dulce'),
    ('Kouign amann',                            0.00, 'Pan dulce'),
    ('Nido cheesecake maracuyá',                0.00, 'Pan dulce'),
    ('Nudo cardamomo',                          0.00, 'Pan dulce'),
    ('Orejita',                                 0.00, 'Pan dulce'),
    ('Panqué chocolate',                        0.00, 'Pan dulce'),
    ('Panqué elote',                            0.00, 'Pan dulce'),
    ('Panqué matcha',                           0.00, 'Pan dulce'),
    ('Panqué plátano',                          0.00, 'Pan dulce'),
    ('Rol canela vegano',                       0.00, 'Pan dulce'),
    ('Rol de cardamomo',                        0.00, 'Pan dulce'),
    ('Scone',                                   0.00, 'Pan dulce'),
    ('Trenza de pistache',                      0.00, 'Pan dulce'),
    ('Baguette',                                0.00, 'Pan salado'),
    ('Campesino ajonjolí',                      0.00, 'Pan salado'),
    ('Campesino de caja ajonjolí (24h extra)',  0.00, 'Pan salado'),
    ('Campesino multigrano',                    0.00, 'Pan salado'),
    ('Ciabatta',                                0.00, 'Pan salado'),
    ('Bagel natural pza',                       0.00, 'Pan y productos por pedido'),
    ('Bagel semillas pza',                      0.00, 'Pan y productos por pedido'),
    ('Baguetin',                                0.00, 'Pan y productos por pedido'),
    ('Base tarta redonda',                      0.00, 'Pan y productos por pedido'),
    ('Bollo brioche hamburguesa',               0.00, 'Pan y productos por pedido'),
    ('Brioche de caja',                         0.00, 'Pan y productos por pedido'),
    ('Charola focaccia',                        0.00, 'Pan y productos por pedido'),
    ('Ganache blanco',                          0.00, 'Pan y productos por pedido'),
    ('Ganache blanco maracuyá',                 0.00, 'Pan y productos por pedido'),
    ('Ganache oscuro',                          0.00, 'Pan y productos por pedido'),
    ('Pan pita',                                0.00, 'Pan y productos por pedido'),
    ('Paq bagels naturales',                    0.00, 'Pan y productos por pedido'),
    ('Paq bagels parmesano',                    0.00, 'Pan y productos por pedido'),
    ('Paq bagels semillas',                     0.00, 'Pan y productos por pedido'),
    ('Higos al vino tinto',                     0.00, 'Congelados y abarrotes'),
    ('Hummus',                                  0.00, 'Congelados y abarrotes'),
    ('Mermelada de frambuesa',                  0.00, 'Congelados y abarrotes'),
    ('Mermelada de higo',                       0.00, 'Congelados y abarrotes'),
    ('Pesto',                                   0.00, 'Congelados y abarrotes'),
    ('Tortillas harina chipotle',               0.00, 'Congelados y abarrotes'),
    ('Tortillas harina integrales',             0.00, 'Congelados y abarrotes'),
    ('Tortillas harina mantequilla',            0.00, 'Congelados y abarrotes'),
    ('Tzatziki',                                0.00, 'Congelados y abarrotes');
