version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: helloprinter_postgres
    environment:
      POSTGRES_USER: hp_admin
      POSTGRES_PASSWORD: hp_secret
      POSTGRES_DB: hp_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  postgres_data:
